theme:
  name: material
site_name: nadl documents

plugins:
- search
- mike
- mkdocstrings:
    handlers:
      python:
        options:
          annotations_path: brief
          docstring_style: google

nav:
- Home : index.md
- API : api.md

watch:
- ../src
